LOGIN_USERNAME = 'input[id="username"]'
LOGIN_PASSWORD = 'input[id="password"]'
LOGIN_BUTTON = '#app > div.sc-gLEhor.dVaUYJ > div > form > button'

NOW = '#nowRoute'
TICKET_REPORT = '#ticketReportsRoute'
EXIBIR_FILTROS_BUTTON = '#app > div.sc-gRtYjc.eQCOlm.d-flex.flex-column.align-items-stretch > div:nth-child(2) > div > div > div.d-flex.align-items-center.justify-content-between.mb-4 > div:nth-child(2) > button'
NOME_FILTER = '#app > div.sc-gRtYjc.eQCOlm.d-flex.flex-column.align-items-stretch > div:nth-child(2) > div > div > div:nth-child(3) > div.sc-gUQvok.goKBGZ.mb-4 > div > div:nth-child(1) > div > input'
EXIBIR_FILTROS_ESTATISTICAS_BUTTON = '#app > div.sc-gRtYjc.eQCOlm.d-flex.flex-column.align-items-stretch > div:nth-child(2) > div > div.d-flex.align-items-center.justify-content-between.mb-4 > div.d-flex > button:nth-child(2)'
INIT_DATE_FILTER = '#app > div.sc-gRtYjc.eQCOlm.d-flex.flex-column.align-items-stretch > div:nth-child(2) > div > div:nth-child(2) > div > div > div:nth-child(2) > div > div > div > div:nth-child(1) > div > input'
END_DATE_FILTER = '#app > div.sc-gRtYjc.eQCOlm.d-flex.flex-column.align-items-stretch > div:nth-child(2) > div > div:nth-child(2) > div > div > div:nth-child(3) > div > div > div > div:nth-child(1) > div > input'
APLICAR_FILTRO_BUTTON = '#app > div.sc-gRtYjc.eQCOlm.d-flex.flex-column.align-items-stretch > div:nth-child(2) > div > div:nth-child(2) > div > div > div:nth-child(12) > div > button'